### PR TITLE
Version 1.4

### PR DESCRIPTION
**Pull request by rakshazi**
Hello,
I merged all patches from @tjaart, @mkljczk, @StrangeAlmond into one PR without conflicts.

Changes:

> 1.4 by @mkljczk
- Infer icon color from color scheme #3 

> 1.3 by @StrangeAlmond
- Added current deaths info
- Fixed coronavirusapi.me
- Added country display on tooltip

> 1.2 by @tjaart
- Fixed lmao.ninja data source

### CODE REVIEW

**Comment by ptrcnull** [comment]
@rakshazi hey, did you even test the PR you submitted...?
obraz

**Comment by ptrcnull** [comment]
like, it's completely broken out of the box
obraz

**Comment by rakshazi** [comment]
@ptrcnull yep, I'm using it right now, actually.
https://instaart.org/storage/m/0435cc59bc9edaf1bf37a87430b321de710d4cdf/208e7f46107414056a0d6f28fc9d381d2cf7fa02/lTXCCsss3sPOFlbE4e6XXWbxDlMrJknjt6cNYD7U.png - screenshot

**Comment by rakshazi** [comment]
I think I know what is the problem - you resized it to one line. Try to set more height

**Comment by ptrcnull** [comment]
it still says:
```
Cases: 0
Deaths: undefined
```

**Comment by rakshazi** [comment]
@ptrcnull sorry, but I can't reproduce that - i have the correct results.
@kacpi2442 sorry, but i just merged multiple forks into one PR and have no idea why is it broken in @ptrcnull case

**Comment by mark-zeroo** [comment]
Just a warning, there's something wrong with the changes I've made that breaks the plasmoid and I haven't had the time to identify the problem.

**Pull request merged**
